image: voegelas/perl-devel-cover

before_script:
  - cpanm --installdeps .

test_job:
  script:
    - cover -delete
    - env HARNESS_PERL_SWITCHES=-MDevel::Cover prove -l
    - cover -select_re ^lib/
